tree_capitator:
  enabled: true
  require_sneaking: true

  limits:
    logs: 32
    leaves: 128

  animation:
    enabled: true
    delay: 1
    logs_per_tick: 1
    leaves_per_tick: 4

  indicator:
    enabled: true
    interval: 5

  effects:
    enabled: true

    particles:
      log_bottom: "kgserver:break1"
      log_top: "kgserver:break2"
      leaf: "kgserver:break1"

      step_y: 0.2

      bottom:
        start_y: -0.9
        end_y: -0.1

      top:
        start_y: 0.1
        end_y: 0.9

    sound:
      name: "kgserver.break.log"
      volume: 0.75
      pitch: 1.0
      interval: 2